Repository jst-seminar-rostlab-tum/truffle-ai-backend, pull requests merged in 2023-05, with the labels that each got.

#7 Back 26: Github trending repos and developers
  ScrapeRepos.cjs
Labels: enhancement

#10 Added the star history feature and transformed the ScrapeRepos into a .ts file
  ScrapeRepos.js
  ScrapeRepos.ts
  package-lock.json
  package.json
Labels: enhancement

#24 [META-53] Update verify-pr-action Version
  .github/workflows/verify-pr.yml
Labels: Verified

#26 [META-55] Update Verify-PR-Action
  .github/workflows/verify-pr.yml
Labels: Verified

#17 [BACK-32] Update star history and add types
  .gitignore
  README.md
  ScrapeRepos.cjs
  package-lock.json
  package.json
  packages/graphql_server/package.json
  packages/graphql_server/src/eli5.ts
  packages/graphql_server/src/scrape-repos.ts
  packages/graphql_server/src/star-history.ts
  packages/graphql_server/src/test/test.ts
  packages/graphql_server/src/types.ts
  packages/graphql_server/src/utils.ts
Labels: enhancement, Verified

#25 [META-54] Create push-to-deploy Github Action for Kubernetes Cluster with Docker containers
  .github/workflows/deploy.yml
  .github/workflows/test-and-build.yml
  .gitignore
  .prettierignore
  config/deployment.template.yml
  docker-compose.yml
  env.sh
  package-lock.json
  package.json
  packages/graphql_gateway/.meshrc.yaml
  packages/graphql_gateway/Dockerfile
  packages/graphql_gateway/package.json
  packages/graphql_server/Dockerfile
  packages/graphql_server/package.json
Labels: Verified

#30 [META-51] Auth workaround
  packages/graphql_gateway/src/envelopPlugins.ts
Labels: Verified

#21 [BACK-46] Create dbUpdater
  package-lock.json
  packages/graphql_server/package.json
  packages/graphql_server/src/api/githubApi.ts
  packages/graphql_server/src/api/openAIApi.ts
  packages/graphql_server/src/dataAggregation.ts
  packages/graphql_server/src/dbUpdater.ts
  packages/graphql_server/src/graphql/resolvers.ts
  packages/graphql_server/src/processRepo.ts
  packages/graphql_server/src/scraping/githubScraping.ts
  packages/graphql_server/src/starHistory/starHistory.ts
  packages/graphql_server/src/starHistory/types.ts
  packages/graphql_server/src/starHistory/utils.ts
  packages/graphql_server/src/supabase.ts
  packages/graphql_server/src/types.ts
  packages/graphql_server/test/dbUpdater.test.ts
  packages/graphql_server/test/test.ts
  packages/graphql_server/types/dataAggregation.d.ts
  packages/graphql_server/types/githubApi.d.ts
  packages/graphql_server/types/githubScraping.d.ts
  packages/graphql_server/types/global.d.ts
  packages/graphql_server/types/openAIApi.d.ts
  packages/graphql_server/types/starHistory.d.ts
  packages/graphql_server/types/supabase.d.ts
Labels: Verified
